variables:
    SolutionBaseName: 'DFC.Compui.Cosmos'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.1
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildTestAndAnalyze
    pool:
      name: NCS - CI and CD
    steps:
    - task: PublishPipelineArtifact@1
      displayName: Publish Apim Policy
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/Notify"
        artifactName: ${{ variables.SolutionBaseName }}.Notify
